# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Active' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Active
  pod 'JTAppleCalendar', '~> 7.1.5'
  pod 'SwiftLint'

  target 'ActiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
